#!/bin/bash

# installation
echo 'installing tmux'
brew install tmux

echo 'installing reattach-to-user-namespace'
brew install reattach-to-user-namespace --with-wrap-pbcopy-and-pbpaste


# terminal customizing
# tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
ln -sfn $PWD/tmux/tmux.conf ~/.tmux.conf


# Bash-it
git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
~/.bash_it/install.sh
source ~/.bash_profile

bash-it enable alias git
bash-it enable completion git
bash-it enable plugin tmux


# themes
mkdir -p ~/.bash_it/themes/sidigdoyo
ln -sfn $PWD/bash_it/themes/sidigdoyo/sidigdoyo.theme.bash ~/.bash_it/themes/sidigdoyo/sidigdoyo.theme.bash

git clone https://github.com/dracula/terminal-app.git dracula

# neovim
# brew install neovim
# mkdir -p ~/.config/nvim/{autoload}
# ln -sfn $PWD/vim/vimrc ~/.config/nvim/init.vim

