#!/usr/bin/env bash

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# NVM
export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"

# aliases
alias j2='cd ~/playground/btpn/jenius'
alias me='cd ~/playground/me'

# functions
function prep() {
  cd ~/playground/btpn/jenius/jenius2-apps
  . prepare-env.sh .env.${1} .env && . run-packager.sh
}


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
